export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const SELECT_FILTER_ARTICLE = 'SELECT_FILTER_ARTICLE'

export const DATE_FILTER_ARTICLE = 'DATE_FILTER_ARTICLE'
