export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const SELECT_ARTICLES = 'SELECT_ARTICLES'
export const FILTER_ARTICLES_BY_DATERANGE = 'FILTER_ARTICLES_BY_DATERANGE'

export const UPDATE_ARTICLE_DATE_RANGE = 'UPDATE_ARTICLE_DATE_RANGE'
